# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdfbc0a051ae3f3545c6e402feca7d777785bdd0991214b88ab40980af840492eec899017a66e7359eb5c6f41b4bd9f1f6e98c3007edee3c120cfcaa2bdbd257

test:
  secret_key_base: 0d19b42defd45097a071cdcba8d12a20253f242e056183c1fe31438b29afa77aee39e3cfaf4d3d1cda9c27674ca5bef9b5380fa175d78bb4f01682798bc3fdd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
